name: Build and Cache japng

on:
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build-japng:
    name: Build japng and upload it to cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout japng repository
        uses: actions/checkout@v4
        with:
          path: japng
          repository: aellerton/japng

      - name: Update Gradle wrapper
        working-directory: japng
        run: |
          sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-4.5-bin.zip|' gradle/wrapper/gradle-wrapper.properties

      - name: Add maven publish plugin
        working-directory: japng
        run: |
          sed -i '/subprojects {/a \    apply plugin: '\''maven-publish'\''\n\n    publishing {\n        publications {\n            maven(MavenPublication) {\n                from components.java\n            }\n        }\n    }' build.gradle

      - name: Add mavenLocal to repositories
        working-directory: japng
        run: sed -i '/repositories {/a \    mavenLocal()' build.gradle

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: '8'

      # Build and install japng to the local Maven repository without tests
      - name: Build and Install
        working-directory: japng
        run: ./gradlew clean build publishToMavenLocal --info -x test

      - name: Debug - List all files in home directory
        run: find ~/.m2

      - name: Check if required Maven files exist
        run: |
          test -f ~/.m2/repository/japng/api/0.5.1/api-0.5.1.pom && echo "api-0.5.1.pom exists" || (echo "api-0.5.1.pom is missing" && exit 1)
          test -f ~/.m2/repository/japng/api/0.5.1/api-0.5.1.jar && echo "api-0.5.1.jar exists" || (echo "api-0.5.1.jar is missing" && exit 1)

      # Update Cache
      - name: Update Cache
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository/japng/api
          key: japng-maven-repo-${{ runner.os }}
