name: Build and Cache japng

on:
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build-japng:
    name: Build japng and upload it to cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout japng repository
        uses: actions/checkout@v4
        with:
          repository: aellerton/japng
          
      - name: Update Gradle wrapper
        run: |
          sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10-bin.zip|' gradle/wrapper/gradle-wrapper.properties

      - name: Add maven publish plugin
        run: |
          sed -i '/subprojects {/a \    apply plugin: '\''maven-publish'\''' build.gradle

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # Build and install japng to the local Maven repository without tests
      - name: Build and Install
        run: ./gradlew clean build publishToMavenLocal -x test

      # Update Cache
      - name: Update Cache
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: japng-maven-repo-${{ runner.os }}
