name: Automatically publish to Modrinth and CurseForge
# This action is triggered when a release is created/published
# The release title is used as version name
# The release tag is used as the version number
# The release description is used as the changelog
on:
  release:
    types: [ published ]

env:
  JAVA_VERSION: 21
  MOD_LOADERS: neoforge
  GAME_VERSIONS: |
    [1.21,1.21.4]
  GAME_VERSION_FILTER: releases
  VERSION_TYPE: release
  PRIMARY_FILE_GLOB: build/libs/SimpleCustomEarlyLoading-*.jar

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    outputs:
      tag_version: ${{ env.TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Extract and process tag version
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ "$TAG" == v* ]]; then
            TAG=${TAG:1}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set version in gradle.properties
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ env.TAG }}/" gradle.properties

      - name: Build Release
        run: ./gradlew build


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ${{ env.PRIMARY_FILE_GLOB }}

  publish-to-github:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      - name: Publish to GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-prerelease: false
          files-primary: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}

  publish-to-curseforge:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1214077
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}

  publish-to-modrinth:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Bi8o4aLw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}